### ISSUE TITLE
the intersection doesn't look right

### ISSUE THREAD

**Issue by minhaj6** [JHMeusener/osm2xodr#13]
![image](https://github.com/user-attachments/assets/d0b40976-549b-45ca-9009-d56c2eb2aacc)

![image](https://github.com/user-attachments/assets/4012de67-775c-44dd-b4f2-ed486c002d46)

The conversion at the intersection doesn't look right. Do you have any suggestions for me? If you can suggest how I can go about editing these maps would be great help. Thank you for your awesome project.

**Comment by JHMeusener** [comment]
Hi Minhaj,
its great that you find my project helpful! To your problem:
Uh, yeah, it does look a bit sketchy. There is definitely a bug in street
direction and lane merging as you can see in the left where a lane merging
went isolated into the wrong lane. Other than that there are a few things i
did not consider before i stopped working on this project:
the lane merging shortly before the intersection may cause havoc as we can
see relatively isolated below, but the worst offender is probably that i
never considered two crossroads be closer than a certain distance together.
since there is a divider in the one street it is mapped in openatreetmaps
as two one-way streets that merge into two crossroads nearly directly side
by side. my algorithm basically draws a circle around each crossroad and
tries to figure out the lanes and behaviour from there. the only fix i
could think of would be to check every crossroad node for distances to
other crossroad nodes and merging them in an intermediate step.
unfortunately i am tied up in other projects to really help you much with
coding a fix. if you have any specific questions about the code i will try
my best to remember what i did and why i did that in order to clarify that
for you.
cheers
Jan

Minhaj Uddin Ahmad ***@***.***> schrieb am Di., 29. Okt.
2024, 20:34:

**Comment by minhaj6** [comment]
Yeah, its a tricky intersection. Anyway, later i tried with sumo `netconvert.py`. It worked pretty well. 
Thank you for your quick response. 

I will share this here - 
![image](https://github.com/user-attachments/assets/e79bb0b8-4c27-46be-b001-406404bce50b)


I did OSM -> OpenDrive (sumo-netconvert) -> Lanelet2 (crdesigner converter). 

I will close this issue here. Do you know of any software where I can have satellite image in the background of a OpenDrive map? 

Thanks!

**Comment by minhaj6** [comment]
![image](https://github.com/user-attachments/assets/c40257b9-9cba-43e4-ba41-ef363244712f)

using odrviewer.io
